### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by a631069724** [micro-in-cn/all-in-one#3]
--------------------------
$curl -H 'Content-Type: application/json' -d '{"name": "小小先"}' "http://localhost:8080/example/call"
curl: (6) Could not resolve host: application
curl: (3) [globbing] unmatched close brace/bracket in column 7
{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}
-----------------------------

-----------------------------
$ go run rpc.go
2019/06/19 11:36:34 Transport [http] Listening on [::]:55590
2019/06/19 11:36:34 Broker [http] Connected to [::]:55591
2019/06/19 11:36:34 Registry [mdns] Registering node: go.micro.api.example-646b118a-e411-490b-a03b-71405df83e25
--------------------------------------------

------------------------
$ micro api --handler=rpc
2019/06/19 11:36:19 Registering RPC Handler at /rpc
2019/06/19 11:36:19 Registering API RPC Handler at /
2019/06/19 11:36:19 HTTP API Listening on [::]:8080
2019/06/19 11:36:19 Transport [http] Listening on [::]:55585
2019/06/19 11:36:19 Broker [http] Connected to [::]:55586
2019/06/19 11:36:19 Registry [mdns] Registering node: go.micro.api-90e88235-d335-4e32-b075-b4c66eef1bab
::1 - - [19/Jun/2019:11:36:55 +0800] "POST /example/call HTTP/1.1" 500 86 "" "curl/7.55.1"
-----------------------

**Comment by printfcoder** [comment]
Hi，可能是你的网络不支持mdns全功能，尝试使用--registry=consul，看是否调用得通

**Comment by a631069724** [comment]
--------------------------------------
$ micro api --handler=rpc
2019/06/21 10:24:26 Registering RPC Handler at /rpc
2019/06/21 10:24:26 Registering API RPC Handler at /
2019/06/21 10:24:26 HTTP API Listening on [::]:8080
2019/06/21 10:24:26 Transport [http] Listening on [::]:52982
2019/06/21 10:24:26 Broker [http] Connected to [::]:52983
2019/06/21 10:24:27 Registry [mdns] Registering node: go.micro.api-5115e6ae-8b27-4ecf-9bbe-5105a1e097c3
::1 - - [21/Jun/2019:10:24:32 +0800] "POST /example/call HTTP/1.1" 500 86 "" "curl/7.64.0"
::1 - - [21/Jun/2019:10:25:27 +0800] "POST /example/call HTTP/1.1" 500 86 "" "curl/7.64.0"
-----------------------------------
$ go run rpc.go --registry=consul
2019/06/21 10:17:36 Transport [http] Listening on [::]:52747
2019/06/21 10:17:36 Broker [http] Connected to [::]:52748
2019/06/21 10:17:37 Registry [consul] Registering node: go.micro.api.example-c14c3b98-a0d5-46ff-87a7-ac54362f20a0
--------------------------------------------
consul 有警告
 2019/06/21 10:27:52 [WARN] agent: Service name "go.micro.api.example" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2019/06/21 10:27:52 [DEBUG] agent: Service tag "t-789caa562a294acc2b2ec82f2a51b252ca28292950aa05040000ffff4f930768" will not be discoverable via DNS due to it being too long. Valid lengths are between 1 and 63 bytes.
---------------

**Comment by printfcoder** [comment]
警告不用管，micro命令也要用consul。`micro --registry=consul api --handler=rpc`

**Comment by a631069724** [comment]
解决了，多谢
